[package]
name = "oddkey"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
rand_core = "0.6"
secp256k1 = { version = "0.29", features = [ "hashes", "global-context", "rand-std", "serde" ] }
